### ISSUE TITLE
remove post truncate for beta 7

### ISSUE THREAD

**Issue by al3xLvs** [mondediefr/fluxbb_to_flarum#1]
cf https://github.com/flarum/core/issues/1044

code:
https://github.com/mondediefr/fluxbb_to_flarum/blob/master/scripts/importer/topics-posts.php#L60-L65

**Comment by al3xLvs** [comment]
voir la PR ici https://github.com/flarum/core/pull/1155
Mais vérifier que ça n'a pas changé pour la beta8

**Comment by hardware** [comment]
Je pense qu'on peut retirer la vérification pour être full compliant beta 7.1
